spring.application.name=redesocial
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/redesocial
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

cors.allowed-origin=http://191.252.38.148

api.security.token.secret=${JWT_SECRET:12345678}

upload.dir=uploads

mailjet.api.key=${MAILJET_ACCESS_KEY}
mailjet.api.secret=${MAILJET_SECRET_KEY}

logging.level.io.awspring.cloud=debug
spring.cloud.aws.region.static=sa-east-1

app.s3.bucket-name=s3-rede-social

spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

