CREATE TABLE public.email_verification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    time_geracao_cod timestamp(6) without time zone,
    codigo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT email_verification_pkey PRIMARY KEY (id)
)