CREATE TABLE public.user_account
(
    confirmacao_email boolean,
    role smallint,
    email_verification_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default",
    user_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_account_pkey PRIMARY KEY (id),
    CONSTRAINT user_account_email_verification_id_key UNIQUE (email_verification_id),
    CONSTRAINT user_account_user_name_key UNIQUE (user_name),
    CONSTRAINT fk_user_account_email_verification_id FOREIGN KEY (email_verification_id)
        REFERENCES public.email_verification (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_account_role_check CHECK (role >= 0 AND role <= 1)
);
