CREATE TABLE public.user_profile
(
    active boolean,
    birth_date date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_account_id bigint,
    bio character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    nickname character varying(255) COLLATE pg_catalog."default",
    photo_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_profile_pkey PRIMARY KEY (id),
    CONSTRAINT user_profile_user_account_id_key UNIQUE (user_account_id),
    CONSTRAINT fk_user_profile_user_account_id FOREIGN KEY (user_account_id)
        REFERENCES public.user_account (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_profile_gender_check CHECK (gender::text = ANY (ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'NON_BINARY'::character varying, 'TRANSGENDER'::character varying, 'AGENDER'::character varying, 'GENDERFLUID'::character varying, 'PREFER_NOT_TO_SAY'::character varying, 'OTHER'::character varying]::text[]))
);
