CREATE TABLE public.user_profile
(
    active boolean,
    birth_date date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint,
    bio character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    photo_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_profile_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_profile_user_account FOREIGN KEY (user_id)
        REFERENCES public.user_account (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
