CREATE TABLE public.post
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    likes integer DEFAULT 0,
    content character varying(5000) COLLATE pg_catalog."default",
    user_profile_id bigint,
    CONSTRAINT post_pkey PRIMARY KEY (id),
    CONSTRAINT fk_post_user_profile_id FOREIGN KEY (user_profile_id)
        REFERENCES public.user_profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);
