CREATE TABLE public.image
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    url character varying(2048) COLLATE pg_catalog."default",
    post_id bigint,
    CONSTRAINT image_pkey PRIMARY KEY (id),
    CONSTRAINT fk_image_post_id FOREIGN KEY (post_id)
        REFERENCES public.post (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
