CREATE TABLE public.connection
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    initiator_id bigint NOT NULL,
    friend_id bigint NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDING',
    created_at timestamp DEFAULT now(),
    accepted_at timestamp,
    is_favorite boolean DEFAULT false,
    notes character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT connection_pkey PRIMARY KEY (id),
    CONSTRAINT fk_connection_initiator FOREIGN KEY (initiator_id)
        REFERENCES public.user_profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_connection_friend FOREIGN KEY (friend_id)
        REFERENCES public.user_profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT connection_status_check CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'BLOCKED'::character varying]::text[]))
);

CREATE UNIQUE INDEX uq_connection_pair 
ON public.connection (initiator_id, friend_id);