CREATE TABLE public.post_like
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    user_profile_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    CONSTRAINT post_like_pkey PRIMARY KEY (id),
    CONSTRAINT fk_post_like_user_profile FOREIGN KEY (user_profile_id)
        REFERENCES public.user_profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_post_like_post FOREIGN KEY (post_id)
        REFERENCES public.post (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
