CREATE TABLE public.visualization
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_profile_id bigint NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT visualization_pkey PRIMARY KEY (id),
    CONSTRAINT fk_visualization_user_profile_id FOREIGN KEY (user_profile_id)
        REFERENCES public.user_profile (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_visualization_post_id FOREIGN KEY (post_id)
        REFERENCES public.post (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
